# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170215_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'permissions': (('view_recipie', "Can see everything we put in our 'food'."),)},
        ),
    ]
