# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170216_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('change_state', "Can change what's happening with the food!"),)},
        ),
    ]
